[package]
name = "prover"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "1.1.2", default-features = false, features = [
    "client",
    "prove",
] }

env_logger = "0.11"

[features]
default = []
cuda = ["risc0-zkvm/cuda"]
